version: "3.9"
services:
  __container__-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/__container__-debug:${TAG}
    expose:
      - 3000
    ports:
      - 9229:9229 # nodejs debug
      - 9230:9230 # nodejs debug
      - 9231:9231 # nodejs debug
      - 3000:3000 # nextjs server
      - 2229:2229 # ssh

  __container__:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}__container__:${TAG}
    expose:
      - 3000
    ports:
      - 3000:3000
