version: "3.9"
services:
  __container__-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/__container__-debug:${TAG}
    expose:
      - 3000
    ports:
      - 9229:9229
      - 9223:9223
      - 3000:3000

  __container__:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}__container__:${TAG}
    expose:
      - 3000
    ports:
      - 3000:3000
